apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - name: webapp-container
        image: docker.io/nginx:1.29.3
        ports:
        - containerPort: 80
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/mydatabase" # Example, adjust based on your MongoDB setup
        volumeMounts:
        - name: web-volume
          mountPath: /data/web
      volumes:
      - name: web-volume
        emptyDir:
          sizeLimit: 5Gi    