apiVersion: v1
kind: Service
metadata:
  name: my-webapp-service
spec:
  type: NodePort # Or ClusterIP if only internal access
  selector:
    app: my-webapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30090
